### ISSUE TITLE
MVN publish problem

### ISSUE THREAD

**Issue by alexeysharandin** [java-embedded-framework/jef#15]
@gastaldi,
regarding discussed here: https://github.com/quarkusio/quarkus/issues/25700
Need your help:

OSSRH - done - https://issues.sonatype.org/browse/OSSRH-81058
GPG config - done.

Now try to understand why I got error in mvn:release: https://github.com/java-embedded-framework/jef/runs/6549699271?check_suite_focus=true

```
Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project JEF: Unable to commit files
Error:  Provider message:
Error:  The git-push command failed.
Error:  Command output:
Error:  Warning: Permanently added the ECDSA host key for IP address '192.30.255.113' to the list of known hosts.
Error:  git@github.com: Permission denied (publickey).
Error:  fatal: Could not read from remote repository.

```

If you able to help - will be very appreciated

**Comment by gastaldi** [comment]
@alexeysharandin you can delete the [maven-settings.xml.gpg](https://github.com/java-embedded-framework/jef/blob/master/.github/release/maven-settings.xml.gpg) file in this repository. The `actions/setup-java` can already create the settings.xml necessary to release. See https://github.com/quarkiverse/quarkus-prettytime/blob/main/.github/workflows/release.yml#L32-L38

**Comment by alexeysharandin** [comment]
@gastaldi 
I see what GPG_PASSPHRASE/GPG_PRIVATE_KEY/OSSRH_TOKEN/OSSRH_USERNAME need to be configured in secrets.*

but as I understood problem somewhere with "git push" command and with GITHUB_TOKEN at this moment.

Is GITHUB_TOKEN = Personal access token with name = "GITHUB_TOKEN" and all permissions or something else?
